### PR TITLE
some edits for consistency

### PR DESCRIPTION
**Pull request by nathanallen**
wip

### CODE REVIEW

**Comment by nathanallen** [comment]
Some thoughts...
- `res.json` is nice and explicit, but `res.send` works for all data types and has the added benefit of being a descriptive verb
- CORS won't be a problem until we're on Heroku. Likewise with `process.ENV.port`.

**Comment by tgaff** [comment]
If they try to access the server from chrome when loading a page from the file system CORS is an issue. curl doesn't care though.

**Comment by tgaff** [comment]
I ran into a problem last semester when using `res.send` instead of `res.json`; I don't recall the specifics of that issue but I believe that res.json sets the Content-Type and does a JSON.stringify.  I like the fact that we're explicitly saying it's JSON here though as I think they're likely equating that with AJAX methods at this point and it makes it clear what's going on (even if it's not a verb).

The one that bothers me more here is that I've got to use `res.sendFile` rather than `res.render` or even the easier but deprecated `res.sendfile`.  That means in total I'm introducing three types of send.  

I could probably skip `.json` and just use res.send and res.sendFile but we'd need to convert everyone over to res.json later anyway.

**Comment by tgaff** [comment]
Anyway, I like your changes!

**Pull request merged**
